FROM apache/airflow:3.3.1

ARG AIRFLOW_VERSION=3.3.1
ARG PYTHON_VERSION=3.12

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt" \
    requests \
    "psycopg[binary]"
